server:
  port: 8080

spring:
  application:
    name: consumer-feign-hystrix-order
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

ribbon:
  ReadTimeout: 5000
feign:
  hystrix:
    enabled: true
